defaults:
    - _self_
    - general : general_default_enzymes
    - model : discrete_enzymes
    - train : train_default_enzymes
    - dataset : enzymes

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}




